- hosts: all
  tasks:
   - name: Hello world
     debug: 
       msg: Hello World
  - name: Copy file from local directory to remote host
      ansible.builtin.copy:
        src: file.txt  
        dest: /home/driss/file.txt  