---
- name: Deploy Service to OpenShift
  hosts: all
  gather_facts: false
  tasks:
    - name: Deploy the service
      kubernetes.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: example-service
          spec:
            selector:
              app: example
            ports:
              - protocol: TCP
                port: 80
                targetPort: 80
            type: ClusterIP
        state: present

    - name: Deploy the deployment
      kubernetes.k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: example-deployment
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: example
            template:
              metadata:
                labels:
                  app: example
              spec:
                containers:
                  - name: example-container
                    image: nginx:latest
                    ports:
                      - containerPort: 80
        state: present
