- name: Deploy Service to OpenShift
  hosts: all
  gather_facts: false
  collections:
    - /var/lib/awx/vendor/awx_ansible_collections/ansible_collections
  tasks:
    - name: Deploy the service
      community.kubernetes.k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: example-deployment
            labels:
              app: example
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: example
            template:
              metadata:
                labels:
                  app: example
              spec:
                containers:
                  - name: example-container
                    image: nginx:latest
                    ports:
                      - containerPort: 80
        state: present
